python -u inference.py \
  --task=flow \
  --data_root=/media/data/datasets \
  --data_list=lists/KITTI_flow_test_2015.txt \
  --context \
  --encoder=dlaup \
  --decoder=hda \
  --batch_size=1 \
  --workers=16 \
  --flow_format=png \
  --model_path=model_zoo/hd3fc_chairs_things_kitti-bfa97911.pth \
  --save_folder=predictions
